### PR TITLE
Remove define_function_peek_compiled

### PR DESCRIPTION
**Pull request by bjorn3**
This adds an `isa` method and returns the code size from `define_function`. This is a nicer way than #651.

### CODE REVIEW

**Comment by bjorn3** [comment]
Travis failed on unrelated rustfmt changes.

**Comment by bjorn3** [comment]
Rebased

**Comment by bnjbvr** [comment]
It's a nice refactoring, and @sunfishcode seemed ok with exposing the ISA on the other issue, so LGTM. Can you rebase just to make sure tests failed only because of formatting, please? Thanks!

**Comment by bjorn3** [comment]
Rebased

**Comment by bnjbvr** [comment]
Great, cheers!

**Pull request merged**
