### PR TITLE
SimpleJit perf map

### PR DESCRIPTION
**Pull request by bjorn3**
Not yet tested

https://lkml.org/lkml/2009/6/8/499

### CODE REVIEW

**Comment by sunfishcode** [comment]
Cool! Would it make sense to make this conditional under `#[cfg(target_os = "linux")]` and the "PERF_BUILDID_DIR" environment variable being set at runtime?

**Comment by bjorn3** [comment]
Tested

**Comment by bjorn3** [comment]
Build fails for rust 1.25, because process::id is not yet stabilised there. What should I do?

**Comment by sunfishcode** [comment]
#569 just landed, so we no longer need to support Rust 1.25 :-).

**Comment by bjorn3** [comment]
can you restart travis?

**Comment by sunfishcode** [comment]
I restarted it, but I think you need to rebase on master for it to pick up the Rust-1.29 change.

**Comment by bjorn3** [comment]
> but I think you need to rebase on master

Of course, done

**Comment by sunfishcode** [comment]
Looks good!

**Pull request merged**
