### PR TITLE
Remove logging levels restrictions

### PR DESCRIPTION
**Pull request by bnjbvr**
See #537 for the reasoning.

### CODE REVIEW

**Comment by sunfishcode** [comment]
With this change, can a program embedding Cranelift still disable trace/debug/info messages at compile time?

**Comment by bnjbvr** [comment]
Yes, the log features chosen by the embedder program will prevail; so if the embedder decides to disable trace/debug/info, it can.

**Comment by sunfishcode** [comment]
Ok, makes sense. We should just document that users can add `features = ["release_max_level_warn"]` or so to their log dependency to reduce code size somewhere. Maybe in the top-level README.md under "Building Cranelift?"

**Comment by bnjbvr** [comment]
Done!

**Comment by sunfishcode** [comment]
Looks good!

**Pull request merged**
