### PR TITLE
Peekable define function

### PR DESCRIPTION
**Pull request by bjorn3**
This is the least intrusive way I could find to get the necessary things for bjorn3/rustc_codegen_cranelift#166.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Is it necessary to call the peek_compiled function before doing the `self.backend.define_function`?

**Comment by bjorn3** [comment]
No, calling it later simplified it a lot.

**Comment by sunfishcode** [comment]
Now that the call is at the end, would it be possible for the caller of `define_function_peek_compiled` to instead call the function itself after `define_function_peek_compiled` returns, rather than passing in a function to be called at the end?

**Comment by bjorn3** [comment]
Hadn't thought about that yet. It will require exposing `code_size` and `isa` though.

**Comment by sunfishcode** [comment]
We could have `define_function` return the `code_size` instead of `()`. And `Module` can provide an accessor to its `isa` if needed, although do you need the whole `isa` or just the `TargetFrontendConfig`? The latter is already available as `module.target_config()`.

**Comment by bjorn3** [comment]
I need the whole isa to get the `encoding_info`.

**Comment by sunfishcode** [comment]
Ok. This PR feels somewhat specialized, and I'd ideally like Cranelift's API to make this kind of thing easier in a more general way, though I don't have any specific ideas at the moment. So let's merge the PR, but keep an eye out for ideas to refactor this :-).

**Pull request merged**
