### PR TITLE
Stackmaps

### PR DESCRIPTION
**Pull request by sunfishcode**
This is the continuation of https://github.com/CraneStation/cranelift/pull/440, rebased and updated to work with Cranelift master.

It contains the basic components of [reference types](https://github.com/WebAssembly/reference-types) support and stackmaps:
 - reference types
 - `isnull` and `null` instructions
 - stackmap instructions indicating places to emit stack maps
 - a stackmaps pass to add stackmap instructions for live reference variables: cranelift-codegen/src/regalloc/stackmaps.rs

### CODE REVIEW

**Comment by bnjbvr** [comment]
Yay! :tada: I'll look at it next week.

**Comment by bnjbvr** [comment]
Sorry for the slow review, it's taken me more than the one week I've promised initially. Since the meta port is almost ready to land, and there's already one rebase conflict that Git can't automatically resolve, would you be ok with waiting after it's landed and rebase your work on top of it?

**Comment by bnjbvr** [comment]
Hi @sunfishcode, this now needs to be rebased after the Python code has been removed, please. Sorry it took time to review this; I was quite eager to have the meta code ported to Rust. I'll do my best to review this in a timely fashion once this has been rebased. Thanks!

**Comment by c27kwan** [comment]
@bnjbvr This change has now been rebased and edited to work with the new Rust meta code. We shouldn't try to merge this anymore since most of it has been replaced. #871 is the new patch.

**Comment by bnjbvr** [comment]
Closing, as discussed with @c27kwan on IRC, this is subsumed by #871. Thanks for the work being done here!

**Pull request closed without merging**
