### PR TITLE
Fix clippy warnings 

### PR DESCRIPTION
**Pull request by yjhmelody**
I find there're so many warnings.

### CODE REVIEW

**Comment by peterhuene** [comment]
Hi @yjhmelody. Thanks for kicking this off. I actually spent a little time today to fix all of the clippy warnings and was going to put the PR up, but you beat me to it :).

Here's [my commit](https://github.com/peterhuene/cranelift/commit/6846e2cabbc8a39ca841f0b58f07daadd74778c1) if you want to cherry pick it on top of your changes and include it in this PR.

**Comment by yjhmelody** [comment]
@peterhuene  what you fixed are more widely than mine. Maybe I should close my PR.
BTW, how to detect such many warnings like what you do? My clippy has not warned me so much.

**Comment by peterhuene** [comment]
@yjhmelody If I do open a separate PR I will rebase on top of your changes so that we don't lose the work you did to help fix this.  But I'm also happy if you want to fetch from my repository and cherry pick that into this PR.

When addressing clippy warnings, I tend to `cargo clean` a lot to ensure it's not skipping over any previously built crates as I go down the list of warnings to fix.

**Comment by bnjbvr** [comment]
Thanks for working on this! Whatever direction you decide to go towards, can you make sure to use descriptive commit messages, and squash formatting commits with the changes they relate to, please? (Happy to have a single commit for this as well!)

**Pull request merged**
