### PR TITLE
[WIP] Don't cache target dir on nightly to prevent old build artifacts from accumulating

### LINKED ISSUE #831: [travis] Don't cache cargo target dir on nightly
Caching the target dir on nightly will cause an accumulation of cached files, as the cargo for one nightly doesn't delete files created by another nightly. This is I think the reason nightly builds on travis take ~50min before timeout instead of `30min like the other channels. It will be necessary to delete all caches afterwards.

### PR DESCRIPTION
**Pull request by bjorn3**
cc #831

### CODE REVIEW

**Comment by bjorn3** [comment]
This seems to be the first PR with the linux nightly job not timing out. The beta linux job did however. @bnjbvr could you please delete all caches once?

**Comment by bnjbvr** [comment]
I've emptied all the caches and restarted beta builds.

**Comment by bjorn3** [comment]
Thanks! All jobs passed!

**Comment by bnjbvr** [comment]
Thanks @bjorn3 ! Actually didn't realize this was still open, and since we've moved to Azure pipelines (which don't seem to show any caching issues), we can close this now.

**Pull request closed without merging**
