### PR TITLE
Errors reported by mypy 0.641 #558

### LINKED ISSUE #558: Errors reported by mypy 0.641
Newly-released mypy 0.641 issues these errors when checking Cranelift's code:
```
cdsl/ti.py:42: error: Too many arguments for "TypeConstraint"
cdsl/ti.py:78: warning: Returning Any from function declared to return "Iterable[TypeVar]"
```
I've [pinned](https://github.com/CraneStation/cranelift/commit/47e8d42f59070aacd07ed81d0fc41cca0fee7d1c) the build to 0.630 to unbreak the CI for now.

### PR DESCRIPTION
**Pull request by theJosher**
Fixes #558 - No more warnings running check.sh with mypy 0.641

### CODE REVIEW

**Comment by theJosher** [comment]
Gladly!

**Comment by theJosher** [comment]
Added commit removing [the workaround](https://github.com/CraneStation/cranelift/commit/47e8d42f59070aacd07ed81d0fc41cca0fee7d1c) from .travis.yml

**Comment by sunfishcode** [comment]
Thanks!

**Comment by theJosher** [comment]
Are there any other issues you could recommend I tackle as a cranelift noob?

**Comment by sunfishcode** [comment]
What areas are you interested in? :-) Are you interested in WebAssembly things, Rust backend things, JIT things, learning to program in Rust in general, or something else?

**Comment by theJosher** [comment]
When you put it that way, my gut says Rust backend, but I am also interested in WebAssembly things, and have a faint interest in JIT things, which I would need to try and see if I take to it or not. I am also new to Rust, but I've never seen language differences as a huge barrier. It is more functional than I'm used to, but it appears to benefit from good documentation and well accepted guidelines.

**Comment by sunfishcode** [comment]
Here are a few ideas:
 - Take a look at [simplejit-demo](https://github.com/CraneStation/simplejit-demo). The toy language it implements is super-minimal, so one way to get started would be to extend it. This could be something simple, like adding a remainder (%) operator, or something a little more involved like adding a switch statement (as soon as cranelift-frontend's new switch support is in a published version on crates.io, which should hopefully be soon). Or just poke around at it and see if there's anything that doesn't make sense -- that's useful feedback too.
 - If you're interested in a data structure puzzle, perhaps take a look at [this TODO](https://github.com/CraneStation/cranelift/blob/master/lib/entity/src/list.rs#L394). The short version is that we want a way to do `reserve` on `EntityList`; for more details on this data structure, see the doc comment on `EntityList`.
 - If you're interested in some more Python stuff, one thing we should do is reduce our usage of `isinstance` and use more regular polymorphism. Look at the `isinstance` calls in lib/codegen/meta-python/gen_encoding.py, for example.
 - Also take a look at [the E-rust](https://github.com/CraneStation/cranelift/labels/E-rust) issues to see if anything there sounds interesting. Regardless of your level of Rust familiarity, take a look and ask questions :-).

**Pull request merged**
