### PR TITLE
Improve graphviz rendering

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by bnjbvr** [comment]
@bjorn3 Can you have a look at the test failure, please?

**Comment by bjorn3** [comment]
Didn't know there were tests for the output. Will update soon.

**Comment by bjorn3** [comment]
Fixed

**Comment by bnjbvr** [comment]
Sorry, there's still a CI failure that seems related.

**Comment by bnjbvr** [comment]
ping @bjorn3 ?

**Comment by bnjbvr** [comment]
Hi @bjorn3! Do you want to rebase this (Github tells me there are small conflicts) and make sure CI passes, or should we close this? Thanks!

**Comment by bjorn3** [comment]
I wont have a lot of time for two weeks, but after that I will rebase and fix it.

**Comment by bjorn3** [comment]
Rebased and fixed tests.

**Comment by bjorn3** [comment]
```bash
$ cargo run -- print-cfg filetests/cfg/loop.clif | dot -Tpng > cfg_graph.png
```

cfg_graph

**Pull request merged**
