### PR TITLE
Update faerie to 0.9.1

### PR DESCRIPTION
**Pull request by bjorn3**
Also update `target-lexicon` to 0.3.0.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Looks like the CI failure is because .travis.yml is still using Rust 1.31. Can you bump it to Rust 1.32?

**Comment by bjorn3** [comment]
Done

**Comment by jgouly** [comment]
The README.md says that we support Rust 1.30 still.

**Comment by bjorn3** [comment]
Updated.

**Comment by bnjbvr** [comment]
LGTM, thanks!

**Pull request merged**
