### PR TITLE
tidy: Remove extra semicolons

### PR DESCRIPTION
**Pull request by fitzgen**
These were causing compilation warnings.

### CODE REVIEW

**Comment by fitzgen** [comment]
Prettyyyy sure the CI failure is not because of this PR :-p

**Comment by abrown** [comment]
Yeah, don't think this broke fuzzing 😄. And it turns out I can re-run those checks. Let's see what happens this time.

**Comment by fitzgen** [comment]
> And it turns out I can re-run those checks. Let's see what happens this time.

Nice! Looks like it's green now :)

**Pull request merged**
