### PR TITLE
Declare br_table otherwise ebb as predecessor

### LINKED ISSUE #545: Regression by #453
cc #453
```
function u0:0(i64, i8) fast {
    ss0 = explicit_slot 4
    ss1 = explicit_slot 16
    ss2 = explicit_slot 4
    ss3 = explicit_slot 4
    ss4 = explicit_slot 4
    ss5 = explicit_slot 4
    ss6 = explicit_slot 4
    ss7 = explicit_slot 4
    ss8 = explicit_slot 4
    ss9 = explicit_slot 4
    ss10 = explicit_slot 1
    ss11 = explicit_slot 2
    ss12 = explicit_slot 1
    ss13 = explicit_slot 16
    ss14 = explicit_slot 4
    ss15 = explicit_slot 2
    sig0 = (i8) -> i8 fast
    sig1 = (i8) -> i8 fast
    sig2 = (i8) -> i8 fast
    sig3 = (i8) -> i8 fast
    fn0 = u0:2664 sig1
    fn1 = u0:2664 sig3
    jt0 = jump_table ebb2, ebb4
ebb0(v0: i64, v1: i8):
    v17 -> v1
    v220 -> v1
    v221 -> v1
    nop 
    v2 = stack_addr.i64 ss0
    v3 = stack_addr.i64 ss1
    v4 = stack_addr.i64 ss2
    v5 = stack_addr.i64 ss3
    v6 = stack_addr.i64 ss4
    v7 = stack_addr.i64 ss5
    v8 = stack_addr.i64 ss6
    v9 = stack_addr.i64 ss7
    v10 = stack_addr.i64 ss8
    v11 = stack_addr.i64 ss9
    v12 = stack_addr.i64 ss10
    v13 = stack_addr.i64 ss11
    v14 = stack_addr.i64 ss12
    v15 = stack_addr.i64 ss13
    v16 = stack_addr.i64 ss14
    jump ebb1
ebb1:
    nop 
    v18 = uextend.i32 v17
    v19 = icmp_imm.i32 uge v18, 34
    brnz.b1 v19, ebb17
    jump ebb16
ebb17:
    v20 = icmp_imm.i32 eq v18, 92
    brnz.b1 v20, ebb5
    v21 = icmp_imm.i32 eq v18, 39
    brnz.b1 v21, ebb6
    v22 = icmp_imm.i32 eq v18, 34
    brnz.b1 v22, ebb7
    jump ebb10(v220)
ebb16:
    v23 = icmp_imm.i32 eq v18, 13
    brnz.b1 v23, ebb3
    v24 = icmp_imm.i32 uge v18, 9
    brnz.b1 v24, ebb18
    jump ebb10(v221)
ebb18:
    v25 = iadd_imm.i32 v18, -9
    br_table v25, ebb10, jt0
    ^~~~~~~ verifier inst35: takes no arguments, but had target ebb10 with 1 arguments
ebb2:
    nop 
    v26 = iconst.i8 92
    v27 = iconst.i64 0
    v28 = imul_imm.i64 v27, 1
    v29 = iadd.i64 v4, v28
    store.i8 v26, v29
    v30 = iconst.i8 116
    v31 = iconst.i64 1
    v32 = imul_imm.i64 v31, 1
    v33 = iadd.i64 v4, v32
    store.i8 v30, v33
    v34 = iconst.i8 0
    v35 = iconst.i64 2
    v36 = imul_imm.i64 v35, 1
    v37 = iadd.i64 v4, v36
    store.i8 v34, v37
    v38 = iconst.i8 0
    v39 = iconst.i64 3
    v40 = imul_imm.i64 v39, 1
    v41 = iadd.i64 v4, v40
    store.i8 v38, v41
    v42 = load.i32 v4
    store.i32 v42, v3
    v43 = iadd_imm.i64 v3, 8
    v44 = iconst.i64 2
    store.i64 v44, v43
    jump ebb12
ebb3:
    nop 
    v45 = iconst.i8 92
    v46 = iconst.i64 0
    v47 = imul_imm.i64 v46, 1
    v48 = iadd.i64 v5, v47
    store.i8 v45, v48
    v49 = iconst.i8 114
    v50 = iconst.i64 1
    v51 = imul_imm.i64 v50, 1
    v52 = iadd.i64 v5, v51
    store.i8 v49, v52
    v53 = iconst.i8 0
    v54 = iconst.i64 2
    v55 = imul_imm.i64 v54, 1
    v56 = iadd.i64 v5, v55
    store.i8 v53, v56
    v57 = iconst.i8 0
    v58 = iconst.i64 3
    v59 = imul_imm.i64 v58, 1
    v60 = iadd.i64 v5, v59
    store.i8 v57, v60
    v61 = load.i32 v5
    store.i32 v61, v3
    v62 = iadd_imm.i64 v3, 8
    v63 = iconst.i64 2
    store.i64 v63, v62
    jump ebb12
ebb4:
    nop 
    v64 = iconst.i8 92
    v65 = iconst.i64 0
    v66 = imul_imm.i64 v65, 1
    v67 = iadd.i64 v6, v66
    store.i8 v64, v67
    v68 = iconst.i8 110
    v69 = iconst.i64 1
    v70 = imul_imm.i64 v69, 1
    v71 = iadd.i64 v6, v70
    store.i8 v68, v71
    v72 = iconst.i8 0
    v73 = iconst.i64 2
    v74 = imul_imm.i64 v73, 1
    v75 = iadd.i64 v6, v74
    store.i8 v72, v75
    v76 = iconst.i8 0
    v77 = iconst.i64 3
    v78 = imul_imm.i64 v77, 1
    v79 = iadd.i64 v6, v78
    store.i8 v76, v79
    v80 = load.i32 v6
    store.i32 v80, v3
    v81 = iadd_imm.i64 v3, 8
    v82 = iconst.i64 2
    store.i64 v82, v81
    jump ebb12
ebb5:
    nop 
    v83 = iconst.i8 92
    v84 = iconst.i64 0
    v85 = imul_imm.i64 v84, 1
    v86 = iadd.i64 v7, v85
    store.i8 v83, v86
    v87 = iconst.i8 92
    v88 = iconst.i64 1
    v89 = imul_imm.i64 v88, 1
    v90 = iadd.i64 v7, v89
    store.i8 v87, v90
    v91 = iconst.i8 0
    v92 = iconst.i64 2
    v93 = imul_imm.i64 v92, 1
    v94 = iadd.i64 v7, v93
    store.i8 v91, v94
    v95 = iconst.i8 0
    v96 = iconst.i64 3
    v97 = imul_imm.i64 v96, 1
    v98 = iadd.i64 v7, v97
    store.i8 v95, v98
    v99 = load.i32 v7
    store.i32 v99, v3
    v100 = iadd_imm.i64 v3, 8
    v101 = iconst.i64 2
    store.i64 v101, v100
    jump ebb12
ebb6:
    nop 
    v102 = iconst.i8 92
    v103 = iconst.i64 0
    v104 = imul_imm.i64 v103, 1
    v105 = iadd.i64 v8, v104
    store.i8 v102, v105
    v106 = iconst.i8 39
    v107 = iconst.i64 1
    v108 = imul_imm.i64 v107, 1
    v109 = iadd.i64 v8, v108
    store.i8 v106, v109
    v110 = iconst.i8 0
    v111 = iconst.i64 2
    v112 = imul_imm.i64 v111, 1
    v113 = iadd.i64 v8, v112
    store.i8 v110, v113
    v114 = iconst.i8 0
    v115 = iconst.i64 3
    v116 = imul_imm.i64 v115, 1
    v117 = iadd.i64 v8, v116
    store.i8 v114, v117
    v118 = load.i32 v8
    store.i32 v118, v3
    v119 = iadd_imm.i64 v3, 8
    v120 = iconst.i64 2
    store.i64 v120, v119
    jump ebb12
ebb7:
    nop 
    v121 = iconst.i8 92
    v122 = iconst.i64 0
    v123 = imul_imm.i64 v122, 1
    v124 = iadd.i64 v9, v123
    store.i8 v121, v124
    v125 = iconst.i8 34
    v126 = iconst.i64 1
    v127 = imul_imm.i64 v126, 1
    v128 = iadd.i64 v9, v127
    store.i8 v125, v128
    v129 = iconst.i8 0
    v130 = iconst.i64 2
    v131 = imul_imm.i64 v130, 1
    v132 = iadd.i64 v9, v131
    store.i8 v129, v132
    v133 = iconst.i8 0
    v134 = iconst.i64 3
    v135 = imul_imm.i64 v134, 1
    v136 = iadd.i64 v9, v135
    store.i8 v133, v136
    v137 = load.i32 v9
    store.i32 v137, v3
    v138 = iadd_imm.i64 v3, 8
    v139 = iconst.i64 2
    store.i64 v139, v138
    jump ebb12
ebb8:
    nop 
    v141 = iconst.i64 0
    v142 = imul_imm.i64 v141, 1
    v143 = iadd.i64 v10, v142
    store.i8 v140, v143
    v144 = iconst.i8 0
    v145 = iconst.i64 1
    v146 = imul_imm.i64 v145, 1
    v147 = iadd.i64 v10, v146
    store.i8 v144, v147
    v148 = iconst.i8 0
    v149 = iconst.i64 2
    v150 = imul_imm.i64 v149, 1
    v151 = iadd.i64 v10, v150
    store.i8 v148, v151
    v152 = iconst.i8 0
    v153 = iconst.i64 3
    v154 = imul_imm.i64 v153, 1
    v155 = iadd.i64 v10, v154
    store.i8 v152, v155
    v156 = load.i32 v10
    store.i32 v156, v3
    v157 = iadd_imm.i64 v3, 8
    v158 = iconst.i64 1
    store.i64 v158, v157
    jump ebb12
ebb9(v159: i8):
    v197 -> v159
    nop 
    v160 = iconst.i32 4
    v161 = ushr.i8 v159, v160
    v162 = iconst.i8 0
    v163 = stack_addr.i64 ss15
    store.i8 v161, v163
    store.i8 v162, v163+1
    v164 = load.i8 v163
    store.i8 v164, v13
    v165 = load.i8 v163+1
    store.i8 v165, v13+1
    v166 = iadd_imm.i64 v13, 1
    v167 = load.i8 v166
    v168 = uextend.i32 v167
    brz.i32 v168, ebb13
    trap user65535
ebb10(v170: i8):
    v177 -> v170
    v140 -> v177
    nop 
    v169 = iconst.i8 32
    v171 = uextend.i64 v169
    v172 = uextend.i64 v170
    v173 = icmp.i64 ule v171, v172
    v174 = bint.i8 v173
    v175 = uextend.i32 v174
    v176 = icmp_imm.i32 eq v175, 0
    brnz.b1 v176, ebb9(v170)
    jump ebb11
ebb11:
    nop 
    v178 = iconst.i8 126
    v179 = uextend.i64 v177
    v180 = uextend.i64 v178
    v181 = icmp.i64 ule v179, v180
    v182 = bint.i8 v181
    v183 = uextend.i32 v182
    v184 = icmp_imm.i32 eq v183, 0
    brnz.b1 v184, ebb9(v177)
    jump ebb8
ebb12:
    nop 
    v185 = load.i32 v3
    store.i32 v185, v2
    v186 = iadd_imm.i64 v3, 8
    v187 = load.i64 v186
    v188 = iconst.i64 0
    store.i64 v188, v15
    v189 = iadd_imm.i64 v15, 8
    store.i64 v187, v189
    v190 = load.i32 v2
    store.i32 v190, v16
    v191 = load.i64 v15
    store.i64 v191, v0
    v192 = load.i64 v15+8
    store.i64 v192, v0+8
    v193 = iadd_imm.i64 v0, 16
    v194 = load.i32 v16
    store.i32 v194, v193
    return
ebb13:
    nop 
    v195 = load.i8 v13
    v196 = call fn0(v195)
    store.i8 v196, v12
    jump ebb14
ebb14:
    nop 
    v198 = iconst.i8 15
    v199 = band.i8 v197, v198
    v200 = call fn1(v199)
    store.i8 v200, v14
    jump ebb15
ebb15:
    nop 
    v201 = iconst.i8 92
    v202 = iconst.i64 0
    v203 = imul_imm.i64 v202, 1
    v204 = iadd.i64 v11, v203
    store.i8 v201, v204
    v205 = iconst.i8 120
    v206 = iconst.i64 1
    v207 = imul_imm.i64 v206, 1
    v208 = iadd.i64 v11, v207
    store.i8 v205, v208
    v209 = iconst.i64 2
    v210 = imul_imm.i64 v209, 1
    v211 = iadd.i64 v11, v210
    v212 = load.i8 v12
    store.i8 v212, v211
    v213 = iconst.i64 3
    v214 = imul_imm.i64 v213, 1
    v215 = iadd.i64 v11, v214
    v216 = load.i8 v14
    store.i8 v216, v215
    v217 = load.i32 v11
    store.i32 v217, v3
    v218 = iadd_imm.i64 v3, 8
    v219 = iconst.i64 4
    store.i64 v219, v218
    jump ebb12
}
```

### PR DESCRIPTION
**Pull request by bjorn3**
fixes #545

### CODE REVIEW

**Comment by bnjbvr** [comment]
Looks like a nice catch, but I'd like @tyler or @sunfishcode confirm this. Maybe we could add a clif test instead of a raw Rust test here?

**Comment by bnjbvr** [comment]
(At least I can confirm this fixes verifier errors I was observing on a few wasm demos including AngryBots, Godot, Embenchen and ZenGarden)

**Comment by bjorn3** [comment]
> Maybe we could add a clif test instead of a raw Rust test here?

This is a error in the frontend, which produces clif ir.

**Comment by sunfishcode** [comment]
This looks good to me. Thanks for tracking this down and fixing it! And I agree that a Rust test makes sense here.

**Pull request merged**
